# Generated by Django 3.2.2 on 2021-05-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='hostel_image2',
            field=models.ImageField(default=' ', upload_to='display/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_images1',
            field=models.ImageField(default='', upload_to='display/img'),
            preserve_default=False,
        ),
    ]
