# Generated by Django 3.2.2 on 2021-05-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_auto_20210518_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='laundry_description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='library',
            name='library_description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
